Try to fix Iter lifetimes
The input must live for at least as long as the output.

Still not quite there though. The lifetime errors have been replaced
with:

  error[E0308]: mismatched types
    --> src/second.rs:85:19
     |
  85 |             next: self.head.map(|node| &node),
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `second::Node`, found struct `std::boxed::Box`
     |
     = note: expected enum `std::option::Option<&second::Node<T>>`
                found enum `std::option::Option<&std::boxed::Box<second::Node<T>>>`

  error[E0308]: mismatched types
    --> src/second.rs:98:25
     |
  98 |             self.next = node.next.map(|node| &node);
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `second::Node`, found struct `std::boxed::Box`
     |
     = note: expected enum `std::option::Option<&'a second::Node<T>>`
                found enum `std::option::Option<&std::boxed::Box<second::Node<T>>>`