Start singly-linked queue version in fifth
As you might expect, it doesn't quite work at first.

  error[E0382]: use of moved value: `new_tail`
    --> src/fifth.rs:36:38
     |
  24 |         let new_tail = Box::new(Node {
     |             -------- move occurs because `new_tail` has type `std::boxed::Box<fifth::Node<T>>`, which does not implement the `Copy` trait
  ...
  31 |         let old_tail = mem::replace(&mut self.tail, Some(new_tail));
     |                                                          -------- value moved here
  ...
  36 |                 old_tail.next = Some(new_tail);
     |                                      ^^^^^^^^ value used here after move