Add Iterator
This fails:

  error[E0521]: borrowed data escapes outside of closure
     --> src/fourth.rs:171:13
      |
  169 |     fn next(&mut self) -> Option<Self::Item> {
      |             --------- `self` declared here, outside of the closure body
  170 |         self.0.take().map(|node_ref| {
  171 |             self.0 = node_ref.next.as_ref().map(|head| head.borrow());
      |             ^^^^^^   -------- borrow is only valid in the closure body
      |             |
      |             reference to `node_ref` escapes the closure body here

  error[E0505]: cannot move out of `node_ref` because it is borrowed
     --> src/fourth.rs:172:22
      |
  169 |     fn next(&mut self) -> Option<Self::Item> {
      |             --------- lifetime `'1` appears in the type of `self`
  170 |         self.0.take().map(|node_ref| {
  171 |             self.0 = node_ref.next.as_ref().map(|head| head.borrow());
      |             ------   -------- borrow of `node_ref` occurs here
      |             |
      |             assignment requires that `node_ref` is borrowed for `'1`
  172 |             Ref::map(node_ref, |node| &node.elem)
      |                      ^^^^^^^^ move out of `node_ref` occurs here