Try to implement pop
Not happy again.

  error[E0507]: cannot move out of `node.next` which is behind a shared reference
    --> src/first.rs:28:29
     |
  28 |                 self.head = node.next;
     |                             ^^^^^^^^^ move occurs because `node.next` has type `first::Link`, which does not implement the `Copy` trait

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0507`.