Try to fix Box references
This fails worse:

  error[E0515]: cannot return reference to local data `*node`
    --> src/second.rs:85:40
     |
  85 |             next: self.head.map(|node| &*node),
     |                                        ^^^^^^ returns a reference to data owned by the current function

  error[E0507]: cannot move out of `self.head` which is behind a shared reference
    --> src/second.rs:85:19
     |
  85 |             next: self.head.map(|node| &*node),
     |                   ^^^^^^^^^
     |                   |
     |                   move occurs because `self.head` has type `std::option::Option<std::boxed::Box<second::Node<T>>>`, which does not implement the `Copy` trait
     |                   help: consider borrowing the `Option`'s content: `self.head.as_ref()`

  error[E0515]: cannot return reference to local data `*node`
    --> src/second.rs:98:46
     |
  98 |             self.next = node.next.map(|node| &*node);
     |                                              ^^^^^^ returns a reference to data owned by the current function

  error[E0507]: cannot move out of `node.next` which is behind a shared reference
    --> src/second.rs:98:25
     |
  98 |             self.next = node.next.map(|node| &*node);
     |                         ^^^^^^^^^
     |                         |
     |                         move occurs because `node.next` has type `std::option::Option<std::boxed::Box<second::Node<T>>>`, which does not implement the `Copy` trait
     |                         help: consider borrowing the `Option`'s content: `node.next.as_ref()`