Fix the use of moved value by using a reference
  error[E0106]: missing lifetime specifier
   --> src/fifth.rs:3:18
    |
  3 |     tail: Option<&mut Node<T>>, // NEW!
    |                  ^ expected named lifetime parameter
    |
  help: consider introducing a named lifetime parameter
    |
  1 | pub struct List<'a, T> {
  2 |     head: Link<T>,
  3 |     tail: Option<&'a mut Node<T>>, // NEW!
    |