Try to add Iter implementation
  error[E0106]: missing lifetime specifier
    --> src/second.rs:74:18
     |
  74 |     next: Option<&Node<T>>,
     |                  ^ expected named lifetime parameter
     |
  help: consider introducing a named lifetime parameter
     |
  73 | pub struct Iter<'a, T> {
  74 |     next: Option<&'a Node<T>>,
     |

  error[E0106]: missing lifetime specifier
    --> src/second.rs:86:17
     |
  86 |     type Item = &T;
     |                 ^ expected named lifetime parameter
     |
  help: consider introducing a named lifetime parameter
     |
  86 |     type Item<'a> = &'a T;
     |              ^^^^   ^^^