Follow the compiler suggestion
It's not quite enough:

  error[E0133]: dereference of raw pointer is unsafe and requires unsafe function or block
    --> src/fifth.rs:32:13
     |
  32 |             (*self.tail).next = Some(new_tail);
     |             ^^^^^^^^^^^^^^^^^ dereference of raw pointer
     |
     = note: raw pointers may be NULL, dangling or unaligned; they can violate aliasing rules and cause data races: all of these are undefined behavior