Try to add pop method
Doesn't work though.

  error[E0507]: cannot move out of `self.head.0` which is behind a mutable reference
    --> src/first.rs:21:15
     |
  21 |         match self.head {
     |               ^^^^^^^^^ help: consider borrowing here: `&self.head`
  22 |             Link::Empty => {}
  23 |             Link::More(node) => {}
     |                        ----
     |                        |
     |                        data moved here
     |                        move occurs because `node` has type `std::boxed::Box<first::Node>`, which does not implement the `Copy` trait

  error: aborting due to previous error; 1 warning emitted

  For more information about this error, try `rustc --explain E0507`.