Try to add push method
Computer Says No.

  error[E0507]: cannot move out of `self.head` which is behind a mutable reference
    --> src/first.rs:13:19
     |
  13 |             next: self.head,
     |                   ^^^^^^^^^ move occurs because `self.head` has type `first::Link`, which does not implement the `Copy` trait

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0507`.
  error: could not compile `lists`.