Try to fix move by borrowing
This results in something that feels like a step backwards 😭

  error[E0308]: mismatched types
    --> src/second.rs:85:19
     |
  85 |             next: self.head.as_ref().map(|node| &*node),
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `second::Node`, found struct `std::boxed::Box`
     |
     = note: expected enum `std::option::Option<&second::Node<T>>`
                found enum `std::option::Option<&std::boxed::Box<second::Node<T>>>`

  error[E0308]: mismatched types
    --> src/second.rs:98:25
     |
  98 |             self.next = node.next.as_ref().map(|node| &*node);
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `second::Node`, found struct `std::boxed::Box`
     |
     = note: expected enum `std::option::Option<&'a second::Node<T>>`
                found enum `std::option::Option<&std::boxed::Box<second::Node<T>>>`