Add lifetime to list
We get a massive error now.

  error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
    --> src/fifth.rs:38:27
     |
  38 |                 self.head.as_mut().map(|node| &mut **node)
     |                           ^^^^^^
     |
  note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 21:5...
    --> src/fifth.rs:21:5
     |
  21 | /     pub fn push(&mut self, elem: T) {
  22 | |         let new_tail = Box::new(Node {
  23 | |             elem: elem,
  24 | |             // When you push onto the tail, your next is always None
  ...  |
  42 | |         self.tail = new_tail;
  43 | |     }
     | |_____^
  note: ...so that reference does not outlive borrowed content
    --> src/fifth.rs:38:17
     |
  38 |                 self.head.as_mut().map(|node| &mut **node)
     |                 ^^^^^^^^^
  note: but, the lifetime must be valid for the lifetime `'a` as defined on the impl at 13:6...
    --> src/fifth.rs:13:6
     |
  13 | impl<'a, T> List<'a, T> {
     |      ^^
  note: ...so that the expression is assignable
    --> src/fifth.rs:42:21
     |
  42 |         self.tail = new_tail;
     |                     ^^^^^^^^
     = note: expected  `std::option::Option<&'a mut fifth::Node<T>>`
                found  `std::option::Option<&mut fifth::Node<T>>`